"""Deploy the Task Orchestrator persistent agent to Microsoft Foundry.

The orchestrator is a Foundry **persistent** agent (PromptAgentDefinition) —
NOT a hosted/container agent. Its sole job is to determine whether the user
wants a Windows or Linux VM and emit a routing marker that the frontend uses
to switch the active SSE target to the matching hosted agent.

Why no tools? Research showed that the current Foundry SDK has no reliable
server-side path to invoke a hosted agent from a persistent agent
(ConnectedAgentTool requires persistent-agent IDs, hosted agents have none;
A2A requires a wrapper server; OpenAPI tool can't reliably inject the
required ``Foundry-Features`` header). The frontend dispatches by parsing
the orchestrator's text output for a JSON marker:

    {"__route__": "windows"}    or    {"__route__": "linux"}

Usage::

    az login
    set FOUNDRY_PROJECT_ENDPOINT=https://multi-agent-demo-6rd2sd.services.ai.azure.com/api/projects/multi-agent-demo-v1
    python deploy/deploy_orchestrator.py

Idempotent: ``create_version`` always creates a new version of the agent;
the agent name (``taskorch-orchestrator``) stays stable so the frontend can
always reference it by name.
"""
from __future__ import annotations

import os
import sys
import time

from azure.ai.projects import AIProjectClient
from azure.ai.projects.models import PromptAgentDefinition
from azure.identity import DefaultAzureCredential

PROJECT_ENDPOINT = (
    os.environ.get("FOUNDRY_PROJECT_ENDPOINT")
    or os.environ["AZURE_AI_PROJECT_ENDPOINT"]
)
MODEL_DEPLOYMENT_NAME = os.environ.get("AZURE_AI_MODEL_DEPLOYMENT_NAME", "gpt-5.1")
ORCHESTRATOR_AGENT_NAME = os.environ.get(
    "ORCHESTRATOR_AGENT_NAME", "taskorch-orchestrator"
)
HOSTED_AGENT_NAME_WINDOWS = os.environ.get(
    "HOSTED_AGENT_NAME_WINDOWS",
    os.environ.get("HOSTED_AGENT_NAME", "vmagent-agent-windows"),
)
HOSTED_AGENT_NAME_LINUX = os.environ.get(
    "HOSTED_AGENT_NAME_LINUX", "vmagent-agent-linux"
)


INSTRUCTIONS = f"""You are the Task Orchestrator. Your job is to figure out
what the user wants and route them to the right specialist agent. There
are three specialists you can route to:

- Windows VM specialist  ({HOSTED_AGENT_NAME_WINDOWS})  — deploys Windows VMs
- Linux VM specialist    ({HOSTED_AGENT_NAME_LINUX})  — deploys Linux VMs
- VM Pricing specialist  (vmagent-agent-pricing)        — quotes monthly cost

You DO NOT perform any deployment work. You DO NOT ask about VM size, region,
networking, image SKU, naming, passwords, or any other configuration. The
specialist agent will handle every one of those questions after handoff.

How to behave
-------------
1. Greet the user briefly the first time you see them. Mention you can help
   them deploy a Windows or Linux VM, or get a monthly cost estimate.
2. If the user has already said "Windows", "Linux", named a specific OS
   (Ubuntu, RHEL, Windows Server, etc.), or asked about cost/pricing, skip
   ahead to step 4.
3. Otherwise, ask exactly ONE short clarifying question (e.g. "Would you
   like to deploy a Windows VM, a Linux VM, or get a cost estimate?").
4. Once you know what they want, output a routing marker on a line by
   itself BEFORE any other text on that turn. The marker MUST be exactly
   one of:

       {{"__route__": "windows"}}
       {{"__route__": "linux"}}
       {{"__route__": "pricing"}}

   Use lowercase. No code fences, no markdown, no extra whitespace inside
   the JSON. Just the raw JSON object on its own line.

5. After the marker line, write one short sentence telling the user which
   specialist will take over (e.g. "Handing you over to the Linux VM
   specialist now."). The frontend switches the conversation to that
   specialist; the user's next message goes directly to them.

Handback messages — IMPORTANT
-----------------------------
A specialist can hand the conversation back to you. When that happens you
will see a USER-role message in your history of the form:

    [handback from <agent-name>: <one short sentence written by the specialist>]

This is a CONTROL message generated by the system, NOT something the user
typed. Examples:

    [handback from vmagent-agent-pricing: Estimated Standard_D2s_v5 Linux in australiaeast at A$95.42/mo. User wants to proceed with Linux build.]
    [handback from vmagent-agent-linux: User changed mind, wants Windows now. Collected vm_name=foo so far.]
    [handback from vmagent-agent-windows: Windows VM foo deployed in rg multi-agent-demo. KV secret URI <uri>.]
    [handback from vmagent-agent-pricing: User abandoned pricing flow without quote.]

Rules for handback messages:

- TREAT them as system-generated context, NOT as user speech.
- NEVER echo the `[handback from ...]` brackets back to the user. They
  didn't write that line and they should not see it.
- ALWAYS produce a response when you receive one — never stay silent.
- React based on the content of the summary:
  * If a deployment finished (success or failure), confirm briefly to the
    user and ask if there's anything else they'd like.
  * If the summary says the user wants a different OS or service,
    IMMEDIATELY emit a routing marker for the right specialist (followed
    by a short "Handing you over to the X specialist now." sentence).
  * If the summary says the user got a price and wants to proceed with
    deployment, route them to the matching VM specialist.
  * If the summary says the user abandoned, ask what they'd like to do
    instead.
- DO NOT re-ask questions the previous specialist already answered.
- Begin your reply with a brief acknowledgement to the user (e.g.
  "Welcome back — I see you priced a D16s_v5 Windows VM. Let me hand you
  to the Windows VM specialist to build it.") then emit the marker if you
  are routing.

Hard rules
----------
- NEVER ask about VM size, region, network, image, naming, password.
- NEVER claim you have deployed anything. You don't deploy.
- ONLY emit a routing marker once you are confident about which specialist.
- If the user asks about anything unrelated to VMs (deploy or price),
  politely redirect: "I can route you to a Windows or Linux VM deployment
  agent, or a pricing agent. Which would you like?"
"""


def main() -> int:
    client = AIProjectClient(
        endpoint=PROJECT_ENDPOINT,
        credential=DefaultAzureCredential(),
        allow_preview=True,
    )

    print(
        f"Creating orchestrator persistent agent: name={ORCHESTRATOR_AGENT_NAME} "
        f"model={MODEL_DEPLOYMENT_NAME}"
    )
    agent = client.agents.create_version(
        agent_name=ORCHESTRATOR_AGENT_NAME,
        description="Routing-only orchestrator: dispatches to Windows or Linux VM hosted agent.",
        definition=PromptAgentDefinition(
            model=MODEL_DEPLOYMENT_NAME,
            instructions=INSTRUCTIONS,
        ),
        metadata={"enableVnextExperience": "true"},
    )
    print(
        f"create_version returned: name={agent.name} "
        f"version={getattr(agent, 'version', '?')}"
    )

    deadline = time.time() + 5 * 60
    last_state = None

    def _state_str(s):
        if s is None:
            return ""
        v = getattr(s, "value", s)
        return str(v).lower()

    while time.time() < deadline:
        v = client.agents.get_version(
            agent_name=ORCHESTRATOR_AGENT_NAME, agent_version=agent.version
        )
        state = getattr(v, "status", None) or getattr(v, "provisioning_state", None)
        if state != last_state:
            print(f"  status={state}")
            last_state = state
        s = _state_str(state)
        if s in ("active", "succeeded"):
            print("Orchestrator active.")
            print(f"AGENT_NAME={ORCHESTRATOR_AGENT_NAME}")
            print(f"AGENT_VERSION={agent.version}")
            return 0
        if s in ("failed", "canceled", "cancelled"):
            print(f"Orchestrator provisioning failed: {state}")
            return 2
        time.sleep(5)
    print("Timed out waiting for orchestrator to become active")
    return 3


if __name__ == "__main__":
    sys.exit(main())
